services:
  postgres:
    image: postgres:17-alpine
    container_name: quotes_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DATABASE_NAME:-quotesDB}
      POSTGRES_USER: ${DATABASE_USER:-admin}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-secret01}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - djangoquotes-data:/var/lib/postgresql/data
    ports:
      - "${DATABASE_PORT:-5432}:5432"

volumes:
  djangoquotes-data: